### ISSUE TITLE
Would you accept PR for some keymaps?

### ISSUE THREAD

**Issue by jondot** [Sewdohe/NeoCode#1]
I'm deliberating forking or contributing (currently on NvChad, but this looks cleaner and slimmer).

For keymaps:

- [ ] ctrl-j/k for telescope navigation/selection
- [ ] faster closing telescope w/ESC
- [ ] shorter livegrep. `ctrl-p`, `ctrl-t` are for command and types (type not existing, replaced by live grep). I think originally from textmate
- [ ] faster write (I use <leader>w)
- [ ] faster close buffer (I use <leader>c)
- [ ] jj for ESC

**Comment by Sewdohe** [comment]
I agree with all the keymaps here minus the crtl-p for live grep, I think it's more useful and intuitive to keep the crtl-p keybind for finding files as that's the vscode default, but yeah all the other keymaps are golden and add convenience 👌

don't you think?

**Comment by Sewdohe** [comment]
Closing due to inactive! Some of these keybinds were implemented
