### ISSUE TITLE
Cool cursor motion

### ISSUE THREAD

**Issue by SingularisArt** [Sewdohe/NeoCode#17]
Hello.

How do you get the cursor animation?
Did you make it yourself using Rust, or from a plugin?

**Comment by Sewdohe** [comment]
The cursor animation is from an application called Neovide. It's just a GUI wrapper around Neovim. What system are you on? A user if this repo made a brew formula for it on macos and you can download the exe from thier github

**Comment by SingularisArt** [comment]
Does it support Arch Linux?

**Comment by Sewdohe** [comment]
> I installed NeoVide.
> How do I create the animation?

Yes, it does

**Comment by SingularisArt** [comment]
Okay. But, how would I create this animation in my custom configuration? I don't want neovim to be a GUI. I want it to pop up in the terminal, not in another window. Would I have to copy the code for this animation and move it to my own custom neovim configuration?

**Comment by Sewdohe** [comment]
> Okay. But, how would I create this animation in my custom configuration? I don't want neovim to be a GUI. I want it to pop up in the terminal, not in another window. Would I have to copy the code for this animation and move it to my own custom neovim configuration?

The terminal environment is not capable of performing the animations, if you want them you will HAVE to use Neovide GUI wrapper.

**Comment by SingularisArt** [comment]
Okay. Thanks for the information.
